### ISSUE TITLE
Regresion Test

### ISSUE THREAD

**Issue by steven-murray** [rasg-affiliates/21cmSense#70] opened 2022-03-11 20:14 UTC
It would be good to have a test where it just runs a full (small) sensitivity calculation and compares against output from @jpober 's original code. We can just store that output in the codebase for testing against.

**Comment by jpober** [comment] 2022-06-03 17:45
I'm not sure I can even run my original code anymore, but I agree this is a very good idea.  Let me know if you're having any issues making headway on it.

**Comment by jpober** [comment] 2023-07-07 13:31
With a lot of handholding (and one critical bug fix), I was able to reproduce the HERA 331 results from HERA Memo 4 (http://reionization.org/wp-content/uploads/2015/05/HERA4_sensecalc.pdf).  The following plots show both sensitivity curves on top of each other (you can really only see one set of points because they overlap) and the absolute difference between them.
![Screenshot 2023-07-05 at 9 28 03 AM](https://github.com/steven-murray/21cmSense/assets/1482671/bcd51331-018f-4ef1-aac8-896680cb4b27)
![Screenshot 2023-07-05 at 9 35 30 AM](https://github.com/steven-murray/21cmSense/assets/1482671/1d1617a9-653c-4a4f-badc-15032cc7856e)
Unfortunately, I think too many tweaks were necessary to make this a routine test.  I had to change the angular diameter distance and H(z) calculations (the old code used the Furlanetto et al. 2006 approximations, not the full ones), the sky noise calculation, and obs_duration, and several other small things.  That said, perhaps once the bug fix is merged in, we can define a reference test using the new code for all future runs of the new code to be compared against.

**Closed** 2024-01-18 10:06 UTC
